version: "3.7"

# create local service environment
services:
  # local database with mysql
  learn-java-mysql:
    image: mysql:8.0
    container_name: learn-java-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/db:/var/lib/mysql